export * from './category'
export * from './customer'
export * from './order'
export * from './page'
export * from './product'
export * from './shop'

export type ConversationStep =
  | 'blank'
  | 'respondGreeting'
  | 'respondCategories'
  | 'respondProducts'
  | 'requestName'
  | 'requestPhone'
  | 'requestAddress'
  | 'requestTransferSlip'
